#!/usr/bin/env bash

set -e
cd `dirname $0`/..

case "$1" in
    development)
        MODE="development"
        CLJSC_OPTS=":optimizations :whitespace, :pretty-print true"
        ;;
    production)
        MODE="production"
        CLJSC_OPTS=":optimizations :advanced"
        ;;
    *)
        echo "Usage: script/build <development|production>"
        exit 1
        ;;
esac

OUT_DIR="out/$MODE"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

source script/classpath.sh

java -cp "$CP" clojure.main \
    lib/clojurescript/bin/cljsc.clj \
    src/cljs \
    "{:output-dir \"$OUT_DIR\" :output-to \"$OUT_DIR/org-html-slides.js\" $CLJSC_OPTS}"

if [ "$MODE" == "production" ]; then
    cp "lib/closure/library/closure/goog/css/common.css" "$OUT_DIR/goog-common.css"
    cp src/css/*.css "$OUT_DIR"
    rm -rf "$OUT_DIR/cljs" "$OUT_DIR/org_html_slides" "$OUT_DIR/domina.js" "$OUT_DIR/one"
fi
