#!/usr/bin/env bash

set -e
cd `dirname $0`/..

case "$1" in
    development)
        MODE="development"
        ;;
    production)
        MODE="production"
        CLJSC_OPTS=":optimizations :advanced"
        ;;
    *)
        echo "Usage: script/build <development|production>"
        exit 1
        ;;
esac

rm -rf out
mkdir -p out


CP="lib/clojurescript/src/clj:lib/clojurescript/src/cljs"
for JAR in lib/*.jar; do
    CP="$CP:$JAR"
done

java -cp "$CP" clojure.main \
    lib/clojurescript/bin/cljsc.clj \
    src/cljs \
    "{:output-to \"out/org-html-slides.js\" $CLJSC_OPTS}"

if [ "$MODE" == "production" ]; then
    cp lib/closure/library/closure/goog/css/common.css out/goog-common.css
    cp src/css/*.css out
fi
