#!/usr/bin/env bash

# ClojureScript is included in this repository as a Git submodule.
#
# This script will pull the latest version of ClojureScript and update
# the submodule. Then you can run `git commit` to update the stored
# ClojureScript commit hash.

set -e
cd `dirname $0`/..

if [ ! -z "`git status --porcelain`" ]; then
    echo "Error: org-html-slides working directory is not clean."
    echo "Commit or stash any uncommitted changes before"
    echo "running this script."
    exit 1
fi

cd lib/clojurescript
if [ ! -z "`git status --porcelain`" ]; then
    echo "Error: ClojureScript working directory is not clean."
    echo "Commit or stash any uncommitted changes before"
    echo "running this script."
    exit 1
fi

git checkout -q master

if git pull | grep 'Already up-to-date' > /dev/null; then
    echo "ClojureScript is already up-to-date."
    exit 0
else
    cd ../..
    git add -f lib/clojurescript
    git commit -m "Update ClojureScript submodule from master."
    echo "ClojureScript updated."
fi
